### ISSUE TITLE
Discardtjek, add a check for hauls on land to the report

### ISSUE THREAD

**Issue by KirstenBirchHaakansson** [DTUAqua/FishLineRapporter#11]

**Comment by jstounberg** [comment]
Tilføjet: Tjek for om sejlruten mellem start og slut poitionen ligger på land er tilføjet, skriver hvis det er tildfældet.

NOTE, der kan selvfølgelig være tilfælde hvor denne bonger falskt ud hvis de fisker rundt om en pynt!
