### ISSUE TITLE
Nye rapport med silde individer

### ISSUE THREAD

**Issue by KirstenBirchHaakansson** [DTUAqua/FishLineRapporter#3]
Få programmet p åQ:\mynd\FiskeLine\Udtræk\SildIndivid lagt op som en Fiskeline rapport - SAS outputtet er ikke nødvendigt

**Comment by jstounberg** [comment]
Raporten er implementeret i fiskeline, og en version er lagt op her under min branch. 
Jeg har bare valgt år som den eneste parameter man kan vælge i fiskeline? 
Eller skal det være på en anden måde med flere muligheder?

**Comment by KirstenBirchHaakansson** [comment]
Tusind tak :-)

Måske man burde kunne vælge art - tror jeg laver et lign. med torsk til Henrik - og måske det også er ok at kunne vælge mange år. Jeg tror jeghavde år på fordi SAS filerne blev så store, men tænker ikke det er et problem med .csv, men måske det er hvis man vælge virkelig mange år.

- Tænker at vi måske kunne lave en folder der hedder personlige i rapport træet og så fx kalde denne individ_fisk_HM - hvad siger du? Så er det lidt lettere for brugere, der bruger Fiskeline sjældent, at finder deres rapport

**Comment by jstounberg** [comment]
Synes det lyder som en god ide med en sådan folder, så er det er også næsten nemmere at lave nye raporter til meget specefikke ting.

Jeg ændre det så man kan vælge art og et span af år
